apiVersion: v1
kind: Service
metadata:
  name: netflix-service
  labels:
    app: nf-app
spec:
  type: NodePort
  ports:
  - port: 4000
    targetPort: 80
    protocol: TCP
    nodePort: 32080
  selector:
    app: nf-app
